// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GovernanceModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GovernanceModule";
  readonly sourceName: "contracts/GovernanceModule.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220bc997ce6fa334ea1ca94a37cc791b37322410e691f8aa8f622056ec6d25e74cf64736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220bc997ce6fa334ea1ca94a37cc791b37322410e691f8aa8f622056ec6d25e74cf64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/GovernanceModule.sol";
  readonly buildInfoId: "solc-0_8_20-6c5bb4731f74581755ba35415c09eb0d4ba5a664";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["GovernanceModule"]: GovernanceModule$Type;
    ["contracts/GovernanceModule.sol:GovernanceModule"]: GovernanceModule$Type;
  }
}