// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Token$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Token";
  readonly sourceName: "contracts/Token.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220dd745d36cff397a6ac8bc86eef030e44e45ce2fc2cb849dc581166e075608e9764736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220dd745d36cff397a6ac8bc86eef030e44e45ce2fc2cb849dc581166e075608e9764736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Token.sol";
  readonly buildInfoId: "solc-0_8_20-6c5bb4731f74581755ba35415c09eb0d4ba5a664";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Token"]: Token$Type;
    ["contracts/Token.sol:Token"]: Token$Type;
  }
}